apiVersion: v1
kind: Service
metadata:
  name: portal 
  namespace: ingress-nginx
  labels:
    app: portal
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: portal
  externalTrafficPolicy: Local
