apiVersion: v1
kind: Service
metadata:
  name: reporting
  namespace: ingress-nginx
  labels:
    app: reporting
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: reporting
  externalTrafficPolicy: Local
