#!/usr/bin/env bash
# Split combined Bamboo plan + plan-permissions specs, then
# write a bamboo.yml with commented !include lines for each plan/perms.
#
# Repo layout expected:
#   <repo-root>/bamboo-specs/                (you run the script here)
#   <repo-root>/bamboo-specs/bamboo-specs/*.yaml   (your spec files)

set -euo pipefail
shopt -s nullglob

INNER_DIR="bamboo-specs"   # inner folder that holds all YAML specs

log(){ printf '[%(%F %T)T] %s\n' -1 "$*"; }

plan_key_from_plan_block() {
  awk '
    BEGIN{inplan=0; pk=""; sk=""}
    /^plan:[[:space:]]*$/ {inplan=1; next}
    inplan && /^[^[:space:]].*:[[:space:]]*$/ {inplan=0}
    inplan {
      if ($0 ~ /^[[:space:]]*project-key:[[:space:]]*/) {
        gsub(/^[[:space:]]*project-key:[[:space:]]*/,"")
        gsub(/^["'\''"]|["'\''"]$/,"")
        pk=$0
      } else if ($0 ~ /^[[:space:]]*key:[[:space:]]*/) {
        gsub(/^[[:space:]]*key:[[:space:]]*/,"")
        gsub(/^["'\''"]|["'\''"]$/,"")
        sk=$0
      }
    }
    END{
      if (sk ~ /-/) { print sk }
      else if (pk != "" && sk != "") { print pk "-" sk }
      else print ""
    }
  ' "$1"
}

write_perms_header() {
  local key="$1" out="$2"
  {
    echo '---'
    echo 'version: 2'
    echo 'plan:'
    echo "  key: $key"
    echo 'plan-permissions:'
  } > "$out"
}

split_by_documents() {
  local in="$1" plan_out="$2" perms_out="$3"
  awk -v P="$plan_out" -v Q="$perms_out" '
    BEGIN{doc=0}
    /^---[[:space:]]*$/ {
      doc++
      if (doc==1) { print "---" > P; next }
      if (doc==2) { print "---" > Q; next }
    }
    { if (doc<2) print >> P; else print >> Q }
  ' "$in"
  grep -q '^plan-permissions:' "$perms_out" || { rm -f "$perms_out" "$plan_out"; return 1; }
}

split_by_block() {
  local in="$1" plan_out="$2" perms_out="$3"
  local tmp_pp=""
  tmp_pp="$(mktemp)"; trap 't=${tmp_pp-}; [[ -n "$t" ]] && rm -f "$t"' RETURN

  awk -v TMP="$tmp_pp" '
    BEGIN{inpp=0}
    /^plan-permissions:[[:space:]]*$/ { inpp=1; print; next }
    inpp {
      if ($0 ~ /^[[:space:]]/) { print >> TMP; print; next }
      inpp=0
    }
    { print }
  ' "$in" > "$plan_out"

  [[ -s "${tmp_pp:-/dev/null}" ]] || { rm -f "${tmp_pp:-}" "$plan_out"; trap - RETURN; return 1; }

  local pkey
  pkey="$(plan_key_from_plan_block "$in")"
  [[ -n "$pkey" ]] || { rm -f "${tmp_pp:-}" "$plan_out"; trap - RETURN; return 1; }

  write_perms_header "$pkey" "$perms_out"
  cat "$tmp_pp" >> "$perms_out"

  awk '
    BEGIN{inpp=0}
    /^plan-permissions:[[:space:]]*$/ { inpp=1; next }
    inpp { if ($0 ~ /^[[:space:]]/) next; inpp=0 }
    { print }
  ' "$plan_out" > "${plan_out}.tmp" && mv "${plan_out}.tmp" "$plan_out"

  rm -f "${tmp_pp:-}"; trap - RETURN
}

generate_bamboo_yml() {
  local yml="bamboo.yml"
  log "Generating $yml (all includes commented)…"
  {
    echo "# Autogenerated include manifest"
    echo "# Uncomment one plan + its perms at a time, commit, and let Bamboo import."
    echo "---"
    echo
    # Use plan files as the authoritative set
    for plan in "$INNER_DIR"/*.plan.yaml; do
      [[ -e "$plan" ]] || continue
      stem="$(basename "$plan" .plan.yaml)"
      rel_plan="$INNER_DIR/$stem.plan.yaml"
      rel_perms="$INNER_DIR/$stem.perms.yaml"
      echo "# !include '$rel_plan'"
      [[ -f "$rel_perms" ]] && echo "# !include '$rel_perms'"
      echo
    done
  } > "$yml"
  grep -q "^# !include" "$yml" && log "Wrote $(grep -c '^# !include' "$yml") commented includes to $yml"
}

main() {
  [[ -d "$INNER_DIR" ]] || { echo "ERROR: Missing inner specs dir: $INNER_DIR" >&2; exit 1; }

  log "Splitting specs in: $INNER_DIR"
  local f base stem plan_out perms_out
  for f in "$INNER_DIR"/*.y{a,}ml; do
    [[ -e "$f" ]] || continue
    base="$(basename "$f")"
    stem="${base%.*}"
    plan_out="$INNER_DIR/${stem}.plan.yaml"
    perms_out="$INNER_DIR/${stem}.perms.yaml"

    # Skip already-split pairs
    if [[ -s "$plan_out" && -s "$perms_out" ]]; then
      log "Skip (already split): $base"
      continue
    fi

    log "Processing: $base"
    if grep -q '^---[[:space:]]*$' "$f" && [ "$(grep -c '^---[[:space:]]*$' "$f")" -ge 2 ]; then
      if split_by_documents "$f" "$plan_out" "$perms_out"; then
        log "  ➜ split by docs"
        continue
      else
        log "  ⚠ doc split missing plan-permissions, falling back to block split"
      fi
    fi

    if grep -q '^plan-permissions:' "$f"; then
      if split_by_block "$f" "$plan_out" "$perms_out"; then
        log "  ➜ split by block"
      else
        log "  ✖ could not split (no plan key / empty perms) — left as-is"
        rm -f "$plan_out" "$perms_out"
      fi
    else
      log "  (no plan-permissions found) — nothing to split"
    fi
  done

  generate_bamboo_yml
  log "Done."
}

main "$@"