apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system

data:
  mapRoles: |
    # ­––– worker-node IAM role –––
    - rolearn: arn:aws:iam::200008295591:role/ingress-nginx-nodes-eks-node-group-20250424001952390900000001
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    # ­––– bastion instance-profile role –––
    - rolearn: arn:aws:iam::200008295591:role/terraform-20250218154025606100000001
      username: bastion
      groups:
        - system:masters        # or another group if you want tighter access


