apiVersion: apps/v1
kind: Deployment
metadata:
  name: conexus-wso2mi
  namespace: wso2mi
spec:
  selector:
    matchLabels:
     app.kubernetes.io/name: conexus-wso2mi
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: conexus-wso2mi
    spec:
      containers:
      - name: conexus-wso2mi
        image: 957770628377.dkr.ecr.us-east-1.amazonaws.com/wso2mi:4.2.0-alpine-0.15
        imagePullPolicy: Always
        env:
         - name: APP_KEY
           valueFrom:
            configMapKeyRef:
              name: micro-config2
              key: app_key
         - name: TENANT_KEY
           valueFrom:
            configMapKeyRef:
              name: micro-config2
              key: tenant_key
         - name: SOCN_PATH
           valueFrom:
            configMapKeyRef:
              name: micro-config2
              key: socn_path

        envFrom:
        - configMapRef:
            name: micro-integrator-config
        ports:
        - containerPort: 8253
        - containerPort: 8290
        - containerPort: 9201
        - containerPort: 9164
      - name: conexus-wso2mi-dashboard
        image: 957770628377.dkr.ecr.us-east-1.amazonaws.com/wso2mi-dashboard:4.2.0-alpine
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: micro-integrator-config
        ports:
        - containerPort: 9743
