apiVersion: v1
kind: Service
metadata:
  name: brms
  labels:
    app.kubernetes.io/name: brms
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: brms
  ports:
    - name: http
      port: 8080
      targetPort: 8080