apiVersion: v1
kind: Service
metadata:
  name: jms
  labels:
    app.kubernetes.io/name: jms
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: jms
  ports:
    - name: http
      port: 8080
      targetPort: 8080