apiVersion: v1
kind: Service
metadata:
  name: reporting
  labels:
    app.kubernetes.io/name: reporting
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: reporting
  ports:
    - name: http
      port: 8080
      targetPort: 8080