apiVersion: v1
kind: Service
metadata:
  name: webservice
  labels:
    app.kubernetes.io/name: webservice
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: webservice
  ports:
    - name: http
      port: 8080
      targetPort: 8080