apiVersion: cert-manager.io/v1
kind: ClusterIssuer # ClusterIssuer can issue for all namespaces
metadata:
  name: letsencrypt-prod-sandbox
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: madhav.kundala@usda.gov
    privateKeySecretRef:
      name: letsencrypt-prod-sandbox
    solvers:
    - http01:
        ingress:
          class: nginx 
