version: 2

plan:
  project-key: AWS
  key: APACHE
  name: Apache Build and Push (AWS)

stages:
  - Build:
      jobs:
        - Build_And_Push

Build_And_Push:
  key: JOB1
  requirements:
    - system.docker.executable
    - system.builder.command.aws
  tasks:
    # Repositories
    - checkout:
        repository: "bamboo-deployment"
        path: bamboo-deployment
        force-clean-build: true
        description: Checkout bamboo-deployment (contains builder.sh)
    - checkout:
        repository: "scripts"
        path: scripts
        force-clean-build: true
        description: Checkout scripts (contains apache Docker context)

    # Ensure bamboo-deployment develop (for consistency with your other plans)
    - script:
        interpreter: BINSH_OR_CMDEXE
        working-dir: bamboo-deployment
        description: Ensure bamboo-deployment branch (develop)
        scripts:
          - |
            set -eu
            git fetch --all --prune
            git checkout -B develop origin/develop || git checkout develop
            git reset --hard origin/develop || true
            git --no-pager log -1 --oneline

    # Sanity – toolchain present
    - script:
        interpreter: BINSH_OR_CMDEXE
        working-dir: bamboo-deployment
        description: Sanity – toolchain present?
        scripts:
          - |
            set -e
            docker --version
            aws --version

    # Build Apache image via builder.sh
    - script:
        interpreter: BINSH_OR_CMDEXE
        working-dir: bamboo-deployment
        description: Build Apache image (staging)
        scripts:
          - |
            set -euo pipefail
            id; groups; stat -c '%U %G %a %n' /var/run/docker.sock
            docker info >/dev/null
            export DOCKER_BUILDKIT=0
            # allow builder to locate scripts/ relative to bamboo-deployment/
            ./builder.sh -s apache
            echo "Built releases:"; ls -1 .release.* || true

    # Compute release name for deployment visibility (optional but consistent)
    - script:
        description: "Compute release name for Deployment"
        interpreter: BINSH_OR_CMDEXE
        working-dir: bamboo-deployment
        scripts:
          - |
            set -eu
            REL_FILE=".release.apache"
            if [ -s "$REL_FILE" ]; then
              REL_TAG="$(head -n1 "$REL_FILE")"
            else
              echo "No apache release tag found, falling back to build number"
              REL_TAG="apache-${bamboo.buildNumber}"
            fi
            echo "release_name=${REL_TAG}" > "${bamboo.build.working.directory}/inject.properties"
            echo "Computed release_name=${REL_TAG}"

    - inject-variables:
        description: "Expose release_name to Deployment"
        file: "inject.properties"
        namespace: "inject"
        scope: RESULT

    # Push image to ECR
    - script:
        interpreter: BINSH_OR_CMDEXE
        working-dir: bamboo-deployment
        description: Push Apache image to ECR
        scripts:
          - |
            set -e
            AWS_REGION="${AWS_REGION:-us-east-1}"
            AWS_ACCOUNT_ID="${AWS_ACCOUNT_ID:-339713019047}"
            ECR_REPO_BASE="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
            APACHE_REPO="${APACHE_ECR_REPO:-conexus-apache}"

            if ! aws ecr get-authorization-token --region "$AWS_REGION" >/dev/null 2>&1; then
              echo "ERROR: missing ecr:GetAuthorizationToken on this role." >&2
              exit 1
            fi
            aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "${ECR_REPO_BASE}"

            : > image-digests.txt
            if [ -f ".release.apache" ]; then
              rel="$(cat .release.apache)"
              local_tag="${LOCAL_APACHE_REPO:-conexus-apache}:${rel}"
              ecr_tag="${ECR_REPO_BASE}/${APACHE_REPO}:${rel}"
              echo "→ Pushing apache : ${rel}"
              docker tag "$local_tag" "$ecr_tag"
              docker push "$ecr_tag"
              dig="$(docker inspect --format='{{index .RepoDigests 0}}' "$ecr_tag" 2>/dev/null || true)"
              [ -n "$dig" ] && echo "apache ${rel} ${dig}" | tee -a image-digests.txt
            else
              echo "No .release.apache found; nothing to push."
              exit 2
            fi

    # Emit image digests
    - script:
        description: Emit image digests
        interpreter: BINSH_OR_CMDEXE
        working-dir: bamboo-deployment
        scripts:
          - |
            set -eu
            [ -f image-digests.txt ] && cat image-digests.txt || echo "<no-digests>"

  artifacts:
    - name: releases
      pattern: "bamboo-deployment/.release.apache"
      required: false
    - name: digests
      pattern: "bamboo-deployment/image-digests.txt"
      required: false

repositories:
  - bamboo-deployment:
      scope: global
  - scripts:
      scope: global

triggers:
  - polling:
      period: "10"