---
version: 2
plan:
  project-key: BT
  key: DPA
  name: DPA - Build

stages:
  - Default Stage:
      manual: false
      final: false
      jobs:
        - Default Job

Default Job:
  key: JOB1
  other:
    clean-working-dir: true
    all-other-apps:
      custom:
        auto: {}
        buildHangingConfig.enabled: "false"

  tasks:
    - checkout:
        force-clean-build: true
        description: Checkout Default Repository

    - checkout:
        repository: bamboo-deployment
        path: bamboo-deployment
        force-clean-build: true
        description: Checkout Default Repository

    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.scripttask:task.builder.script
        configuration:
          interpreter: BINSH_OR_CMDEXE
          inlineBody: |
            rm -rf ~/.m2/repository/gov/gsa/
        description: Remove existing cnxs maven repo directory

    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.scripttask:task.builder.script
        configuration:
          interpreter: SHELL
          scriptFile: bamboo-deployment/build-determination-migration.sh
        description: Determine parent branch and pass correct variables

    - inject-variables:
        file: file.properties
        scope: LOCAL
        namespace: inject
        description: Inject values

    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.bamboo-variable-inject-plugin:dump
        configuration: {}

    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.maven:task.maven
        configuration:
          executable: Maven 3
          jdk: JDK 17
          goal: >
            clean verify -B -U -P integration-test
            -Dbamboo.inject.BranchName=${bamboo.inject.BranchName}
            -Dbamboo.inject.mavenFeatureRepositoryUrl=${bamboo.inject.mavenFeatureRepositoryUrl}
            -Dbamboo.inject.pluginRepositoryUrl=${bamboo.inject.pluginRepositoryUrl}
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          tests: "**/target/surefire-reports/*.xml,**/target/failsafe-reports/*.xml"

    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.variable.updater.variable-updater-generic:variable-extractor
        configuration:
          variable: maven.version
          variableScope: RESULT

    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.scripttask:task.builder.script
        configuration:
          interpreter: SHELL
          scriptFile: bamboo-deployment/deploy-to-artifactory-and-create-bamboo-version-migrate.sh
          environmentVariables: |
            buildVersionQueryArtifact=${bamboo.buildVersionQueryArtifact}
            buildVersionQueryGroup=${bamboo.buildVersionQueryGroup}
            mavenVersion=${bamboo.maven.version}
        description: Deploy to Artifactory if needed

    - inject-variables:
        file: file.properties
        scope: RESULT
        namespace: inject
        description: Inject build info for Bamboo Deploy

    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.bamboo-variable-inject-plugin:dump
        configuration: {}

  artifact-subscriptions: []

variables:
  buildVersionQueryArtifact: dpa-ear
  buildVersionQueryGroup: gov.gsa.cnxs.dpa

repositories:
  - DPA:
      scope: global
  - bamboo-deployment:
      scope: global

triggers:
  - bitbucket-server-trigger:
      repositories:
        - DPA

branches:
  create: for-new-branch
  delete:
    after-deleted-days: 7
    after-inactive-days: 200
  link-to-jira: true

notifications:
  - events:
      - plan-failed
    recipients:
      - responsible
      - committers

  - events:
      - plan-completed
    recipients:
      - watchers

labels: []

dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: none
  plans: []
---
version: 2
plan:
  key: BT-DPA

plan-permissions:
  - users:
      - jeff.sikala
    groups:
      - bamboo-admin
    permissions:
      - view
      - edit
      - build
      - clone
      - admin
      - view-configuration