---
version: 2
plan:
  project-key: BT
  key: DPA
  name: DPA - Build

stages:
  - Default Stage:
      manual: false
      final: false
      jobs:
        - Default Job

Default Job:
  key: JOB1
  other:
    clean-working-dir: true
    all-other-apps:
      custom:
        auto: {}
        buildHangingConfig.enabled: 'false'

  tasks:
    - checkout:
        force-clean-build: true
        description: Checkout Default Repository

    - checkout:
        repository: bamboo-deployment
        path: bamboo-deployment
        force-clean-build: true
        description: Checkout bamboo-deployment

    - script:
        interpreter: BINSH_OR_CMDEXE
        scripts:
          - rm -rf ~/.m2/repository/gov/gsa/
        description: Remove existing cnxs maven repo directory

    - script:
        interpreter: SHELL
        file: bamboo-deployment/build-determination-migration.sh
        description: Determine parent branch and pass correct variables

    - inject-variables:
        file: file.properties
        scope: LOCAL
        namespace: inject
        description: Inject values

    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.bamboo-variable-inject-plugin:dump
        configuration: {}

    - script:
        interpreter: SHELL
        scripts:
          - |-
            cat > settings-artifactory.xml <<XML
            <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0">
              <mirrors>
                <mirror>
                  <id>ArtifactoryPluginRepos</id>
                  <mirrorOf>*,!conexus-snapshot-local</mirrorOf>
                  <url>${bamboo.inject.pluginRepositoryUrl}</url>
                </mirror>
              </mirrors>

              <profiles>
                <profile>
                  <id>use-artifactory</id>
                  <repositories>
                    <repository>
                      <id>conexus-plugin-repository</id>
                      <url>${bamboo.inject.pluginRepositoryUrl}</url>
                      <releases><enabled>true</enabled></releases>
                      <snapshots><enabled>true</enabled></snapshots>
                    </repository>
                    <repository>
                      <id>conexus-snapshot-local</id>
                      <url>${bamboo.inject.mavenFeatureRepositoryUrl}</url>
                      <releases><enabled>false</enabled></releases>
                      <snapshots><enabled>true</enabled></snapshots>
                    </repository>
                  </repositories>

                  <pluginRepositories>
                    <pluginRepository>
                      <id>conexus-plugin-repository</id>
                      <url>${bamboo.inject.pluginRepositoryUrl}</url>
                      <releases><enabled>true</enabled></releases>
                      <snapshots><enabled>true</enabled></snapshots>
                    </pluginRepository>
                  </pluginRepositories>
                </profile>
              </profiles>

              <activeProfiles>
                <activeProfile>use-artifactory</activeProfile>
              </activeProfiles>

              <servers>
                <server>
                  <id>cnxs-artifactory</id>
                  <username>sa_bamboo</username>
                  <password>${bamboo.artifactory_access_token_secret}</password>
                </server>
                <server>
                  <id>artifactory</id>
                  <username>sa_bamboo</username>
                  <password>${bamboo.artifactory_access_token_secret}</password>
                </server>
                <server>
                  <id>conexus-plugin-repository</id>
                  <username>sa_bamboo</username>
                  <password>${bamboo.artifactory_access_token_secret}</password>
                </server>
                <server>
                  <id>conexus-snapshot-local</id>
                  <username>sa_bamboo</username>
                  <password>${bamboo.artifactory_access_token_secret}</password>
                </server>
                <server>
                  <id>ArtifactoryPluginRepos</id>
                  <username>sa_bamboo</username>
                  <password>${bamboo.artifactory_access_token_secret}</password>
                </server>
                <server>
                  <id>ArtifactoryMavenFeatureRepos</id>
                  <username>sa_bamboo</username>
                  <password>${bamboo.artifactory_access_token_secret}</password>
                </server>
              </servers>
            </settings>
            XML
        description: Write Artifactory Maven settings

    - maven:
        executable: Maven 3
        jdk: JDK 17
        goal: >-
          clean verify -B -U
          -s settings-artifactory.xml
          -Dbamboo.inject.BranchName=${bamboo.inject.BranchName}
          -Dbamboo.inject.mavenFeatureRepositoryUrl=${bamboo.inject.mavenFeatureRepositoryUrl}
          -Dbamboo.inject.pluginRepositoryUrl=${bamboo.inject.pluginRepositoryUrl}
          -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        tests: '**/target/surefire-reports/*.xml,**/target/failsafe-reports/*.xml'
        description: Build and Verify

    - script:
        interpreter: SHELL
        file: bamboo-deployment/deploy-to-artifactory-and-create-bamboo-version-migrate.sh
        environment: >-
          buildVersionQueryArtifact=${bamboo.buildVersionQueryArtifact}
          buildVersionQueryGroup=${bamboo.buildVersionQueryGroup}
          deployablePomPath=dpa-ear/pom.xml
        description: Deploy to Artifactory if needed

    - inject-variables:
        file: file.properties
        scope: RESULT
        namespace: inject
        description: Inject the build information to be used in Bamboo Deploy

    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.bamboo-variable-inject-plugin:dump
        configuration: {}

  artifacts:
    - name: dpa-ear
      location: dpa-ear/target
      pattern: nsfs-dpa-ear.ear
      shared: true
      required: true

  artifact-subscriptions: []

variables:
  buildVersionQueryArtifact: dpa-ear
  buildVersionQueryGroup: gov.gsa.cnxs.dpa

repositories:
  - DPA:
      scope: global
  - bamboo-deployment:
      scope: global

triggers:
  - bitbucket-server-trigger:
      repositories:
        - DPA

branches:
  create: for-new-branch
  delete:
    after-deleted-days: 7
    after-inactive-days: 200
  link-to-jira: true

notifications:
  - events:
      - plan-failed
    recipients:
      - responsible
      - committers

  - events:
      - plan-completed
    recipients:
      - watchers

  - events:
      - plan-failed
    recipients:
      - responsible
      - committers

labels: []

dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: none
  plans: []

other:
  concurrent-build-plugin:
    number-of-concurrent-builds: system-default
    execution-strategy: block-triggering