---
version: 2
plan:
  project-key: BT
  key: RNT
  name: Rest - Nightly Testing

stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Default Job

Default Job:
  key: JOB1
  tasks:
  - clean

  # Checkouts
  - checkout:
      force-clean-build: true
      description: Checkout Default Repository
  - checkout:
      repository: bamboo-deployment
      path: bamboo-deployment
      force-clean-build: true
      description: Checkout Default Repository

  # Optional cache hygiene
  - script:
      interpreter: BINSH_OR_CMDEXE
      scripts:
      - rm -rf ~/.m2/repository/gov/gsa/
      description: Remove existing cnxs maven repo directory

  # Use migrated scripts from CNXS-62536
  - script:
      interpreter: SHELL
      scripts:
      - |
        set -e
        cd bamboo-deployment
        git fetch --all --prune
        git checkout -B CNXS-62536 origin/CNXS-62536 || git checkout -B CNXS-62536
        git log -1 --oneline
      description: Ensure bamboo-deployment@CNXS-62536 branch

  # Discover endpoints & write settings-ca.xml + file.properties
  - script:
      interpreter: SHELL
      file: bamboo-deployment/build-determination-migration.sh
      description: Determine parent branch and pass correct variables

  # Fetch a short-lived CodeArtifact token (LOCAL scope)
  - script:
      interpreter: SHELL
      scripts:
      - |
        set +x
        echo "caToken=$(aws codeartifact get-authorization-token \
          --domain cnxsartifact --query authorizationToken --output text --region us-east-1)" > ca-token.properties
      description: Fetch CodeArtifact token (local)

  # Inject endpoints and token
  - inject-variables:
      file: file.properties
      scope: LOCAL
      namespace: inject
      description: Inject values
  - inject-variables:
      file: ca-token.properties
      scope: LOCAL
      description: Inject CodeArtifact token

  - any-task:
      plugin-key: com.atlassian.bamboo.plugins.bamboo-variable-inject-plugin:dump
      configuration: {}

  # Nightly build via Script so we can export the token and apply memory/log flags
  - script:
      interpreter: SHELL
      scripts:
      - |
        set -e
        export CODEARTIFACT_AUTH_TOKEN="${bamboo.caToken}"
        export MAVEN_OPTS="-Xms512m -Xmx1024m -Dorg.slf4j.simpleLogger.defaultLogLevel=info"
        mvn -s settings-ca.xml \
          clean verify -B -U -P nightly-integration-test \
          -Dbamboo.inject.BranchName=${bamboo.inject.BranchName} \
          -Dbamboo.inject.mavenFeatureRepositoryUrl=${bamboo.inject.mavenFeatureRepositoryUrl} \
          -Dbamboo.inject.pluginRepositoryUrl=${bamboo.inject.pluginRepositoryUrl} \
          -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      description: Nightly Build and Verify (CodeArtifact)

  # (Optional but recommended) Parse surefire/failsafe results
  - test-parser:
      type: junit
      ignore-time: false
      test-results: "**/target/surefire-reports/*.xml"
      description: surefire reports
  - test-parser:
      type: junit
      ignore-time: false
      test-results: "**/target/failsafe-reports/*.xml"
      description: failsafe reports

repositories:
- Rest:
    scope: global
- bamboo-deployment:
    scope: global

triggers: []   # Nightly schedule can be added in UI or provided as cron if your Bamboo version supports it

branches:
  create: manually
  delete:
    after-deleted-days: 7
    after-inactive-days: 200
  link-to-jira: true

notifications:
- events: [plan-completed]
  recipients: [watchers]
- events: [plan-failed]
  recipients: [responsible, committers]

labels: []

dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: none
  plans: []