---
version: 2
plan:
  project-key: BT
  key: RNT
  name: Rest - Nightly Testing
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Default Job
Default Job:
  key: JOB1
  other:
    clean-working-dir: true
    all-other-apps:
      custom.buildHangingConfig.enabled: 'false'
  tasks:
  - checkout:
      force-clean-build: true
      description: Checkout Default Repository
  - checkout:
      repository: bamboo-deployment
      path: bamboo-deployment
      force-clean-build: true
      description: Checkout bamboo-deployment
  - script:
      interpreter: BINSH_OR_CMDEXE
      scripts:
      - |-
        dirName=~/.m2/repository/gov/gsa/cnxs/
        if [ -d "$dirName" ]; then
          echo "Removing snapshot folders from $dirName"
          find "$dirName" -type d -name '*SNAPSHOT' -exec rm -rf {} +
        fi
      description: Remove existing cnxs maven repo directory
  - script:
      interpreter: SHELL
      file: bamboo-deployment/build-determination-migration.sh
      description: Determine parent branch and pass correct variables
  - inject-variables:
      file: file.properties
      scope: LOCAL
      namespace: inject
      description: Inject values
  - any-task:
      plugin-key: com.atlassian.bamboo.plugins.bamboo-variable-inject-plugin:dump
      configuration: {}
      description: Dump variables to log
  - maven:
      executable: Maven 3
      jdk: JDK 17
      goal: clean verify -B -U -P nightly-integration-test -DskipSurefire=true -Dbamboo.inject.BranchName=${bamboo.inject.BranchName} -Dbamboo.inject.mavenFeatureRepositoryUrl=${bamboo.inject.mavenFeatureRepositoryUrl} -Dbamboo.inject.pluginRepositoryUrl=${bamboo.inject.pluginRepositoryUrl} -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      tests: 'true'
      environment: MAVEN_OPTS="-Xms512m -Xmx1024m -Dorg.slf4j.simpleLogger.defaultLogLevel=info"
      description: Build and Verify
  artifact-subscriptions: []
  artifacts:
  - name: Jboss Log
    location: integration/target
    pattern: jboss.log
    shared: true
    required: false
  - name: Postgres Log
    location: integration/target
    pattern: postgres.log
    shared: true
    required: false
repositories:
- Rest:
    scope: global
- bamboo-deployment:
    scope: global
triggers:
- cron:
    expression: 0 0 1 ? * *
    description: Nightly 1 AM trigger
branches:
  create: manually
  delete:
    after-deleted-days: 7
    after-inactive-days: 200
  link-to-jira: true
notifications:
- events:
  - plan-completed
  recipients:
  - watchers
- events:
  - plan-failed
  recipients:
  - responsible
  - committers
labels: []
dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: none
  plans: []
other:
  concurrent-build-plugin:
    number-of-concurrent-builds: system-default
    execution-strategy: block-triggering
  force-stop-build: true