---
version: 2
plan:
  project-key: BT
  key: VE
  name: Vendor Emulator - Build

stages:
  - Default Stage:
      manual: false
      final: false
      jobs:
        - Default Job

Default Job:
  key: JOB1
  tasks:
    - clean

    # Repositories
    - checkout:
        force-clean-build: true
        description: Checkout Default Repository
    - checkout:
        repository: bamboo-deployment
        path: bamboo-deployment
        force-clean-build: true
        description: Checkout bamboo-deployment

    # Optional cache hygiene
    - script:
        interpreter: BINSH_OR_CMDEXE
        scripts:
          - rm -rf ~/.m2/repository/gov/gsa/
        description: Remove existing cnxs maven repo directory

    # Pin bamboo-deployment to develop (or BAMBOO_DEPLOYMENT_BRANCH if set)
    - script:
        interpreter: SHELL
        working-dir: bamboo-deployment
        scripts:
          - |
            /usr/bin/env bash <<'BASH'
            set -euo pipefail
            TARGET_BRANCH="${BAMBOO_DEPLOYMENT_BRANCH:-develop}"
            echo "Target branch: ${TARGET_BRANCH}"

            if ! git show-ref --verify --quiet "refs/remotes/origin/${TARGET_BRANCH}"; then
              git fetch --prune origin "refs/heads/${TARGET_BRANCH}:refs/remotes/origin/${TARGET_BRANCH}" || {
                echo "ERROR: could not fetch origin/${TARGET_BRANCH}"; git ls-remote --heads origin || true; exit 3; }
            fi

            git checkout -B "${TARGET_BRANCH}" "origin/${TARGET_BRANCH}"
            test -f build-determination-migration.sh || { echo "build-determination-migration.sh not found"; ls -la; exit 4; }
            chmod +x build-determination-migration.sh
            BASH
        description: Ensure bamboo-deployment@develop branch + script present

    # Discover endpoints (runs inside bamboo-deployment/)
    - script:
        interpreter: SHELL
        working-dir: bamboo-deployment
        file: build-determination-migration.sh
        description: Determine parent branch and pass correct variables

    # Export the generated files to the job root for downstream tasks
    - script:
        interpreter: SHELL
        scripts:
          - |
            set -e
            cp bamboo-deployment/file.properties . || { echo "Missing bamboo-deployment/file.properties"; ls -la bamboo-deployment; exit 5; }
            cp -f bamboo-deployment/settings-ca.xml . || { echo "Missing bamboo-deployment/settings-ca.xml"; ls -la bamboo-deployment; exit 6; }
            ls -la file.properties settings-ca.xml
        description: Export properties & settings to workspace root

    # Make endpoints available to later tasks
    - inject-variables:
        file: file.properties
        scope: LOCAL
        namespace: inject
        description: Inject values

    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.bamboo-variable-inject-plugin:dump
        configuration: {}

    # Fetch a short-lived CodeArtifact token to local file (no Bamboo var leaks)
    - script:
        interpreter: SHELL
        scripts:
          - |
            set -e
            TOKEN="$(aws codeartifact get-authorization-token \
              --domain cnxsartifact --query authorizationToken --output text --region us-east-1)"
            [ -n "$TOKEN" ] || { echo "ERROR: empty CodeArtifact token"; exit 1; }
            printf 'caToken.password=%s\n' "$TOKEN" > ca-token.properties
            chmod 600 ca-token.properties
            echo "Wrote ca-token.properties"
        description: Fetch CodeArtifact token (local file only)

    # Write final Maven settings with resolve + deps repos using env-token interpolation
    - script:
        interpreter: BINSH_OR_CMDEXE
        scripts:
          - |
            set -e
            export CODEARTIFACT_AUTH_TOKEN="$(awk -F= '/^caToken[.]password=/{print $2}' ca-token.properties | tr -d '\r\n')"
            [ -n "${CODEARTIFACT_AUTH_TOKEN:-}" ] || { echo "ERROR: CodeArtifact token missing"; exit 1; }

            RESOLVE_URL="${bamboo_inject_resolveRepositoryUrl:?missing resolveRepositoryUrl}"
            # Derive deps endpoint alongside resolve (conexus-dependencies)
            DEPS_URL="$(printf '%s' "$RESOLVE_URL" | sed -E 's#/maven/[^/]+/#/maven/conexus-dependencies/#')"

            cat > settings-final.xml <<XML
            <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
              <servers>
                <server>
                  <id>ca-resolve</id>
                  <username>aws</username>
                  <password>\${env.CODEARTIFACT_AUTH_TOKEN}</password>
                </server>
                <server>
                  <id>ca-deps</id>
                  <username>aws</username>
                  <password>\${env.CODEARTIFACT_AUTH_TOKEN}</password>
                </server>
              </servers>
              <profiles>
                <profile>
                  <id>codeartifact</id>
                  <repositories>
                    <repository>
                      <id>ca-resolve</id>
                      <url>${RESOLVE_URL}</url>
                      <releases><enabled>true</enabled></releases>
                      <snapshots><enabled>true</enabled></snapshots>
                    </repository>
                    <repository>
                      <id>ca-deps</id>
                      <url>${DEPS_URL}</url>
                      <releases><enabled>true</enabled></releases>
                      <snapshots><enabled>true</enabled></snapshots>
                    </repository>
                  </repositories>
                  <pluginRepositories>
                    <pluginRepository>
                      <id>ca-resolve</id>
                      <url>${RESOLVE_URL}</url>
                      <releases><enabled>true</enabled></releases>
                      <snapshots><enabled>true</enabled></snapshots>
                    </pluginRepository>
                    <pluginRepository>
                      <id>ca-deps</id>
                      <url>${DEPS_URL}</url>
                      <releases><enabled>true</enabled></releases>
                      <snapshots><enabled>true</enabled></snapshots>
                    </pluginRepository>
                  </pluginRepositories>
                </profile>
              </profiles>
              <activeProfiles>
                <activeProfile>codeartifact</activeProfile>
              </activeProfiles>
            </settings>
            XML
            echo "Wrote settings-final.xml (resolve=${RESOLVE_URL} deps=${DEPS_URL})"
        description: Write final Maven settings (resolve + deps)

    # -------- Preflight check for parent BOM in CodeArtifact (explicit GAV + both repos) --------
    - script:
        interpreter: BINSH_OR_CMDEXE
        scripts:
          - |
            set -e
            # Load token from local file
            export CODEARTIFACT_AUTH_TOKEN="$(awk -F= '/^caToken[.]password=/{print $2}' ca-token.properties | tr -d '\r\n')"
            [ -n "${CODEARTIFACT_AUTH_TOKEN:-}" ] || { echo "ERROR: CodeArtifact token missing"; exit 1; }

            SETTINGS_PATH="$(pwd -P)/settings-final.xml"
            [ -f "$SETTINGS_PATH" ] || { echo "ERROR: $SETTINGS_PATH not found"; exit 1; }

            RESOLVE_URL="${bamboo_inject_resolveRepositoryUrl:?missing resolveRepositoryUrl}"
            DEPS_URL="$(printf '%s' "$RESOLVE_URL" | sed -E 's#/maven/[^/]+/#/maven/conexus-dependencies/#')"

            # Parse <parent> GAV from project POM
            PARENT_BLOCK="$(awk 'BEGIN{RS="</parent>";FS=RS} /<parent>/{print; exit}' pom.xml || true)"
            PARENT_G="$(printf '%s' "$PARENT_BLOCK" | awk -F'[<>]' '/<groupId>/{print $3; exit}' || true)"
            PARENT_A="$(printf '%s' "$PARENT_BLOCK" | awk -F'[<>]' '/<artifactId>/{print $3; exit}' || true)"
            PARENT_V="$(printf '%s' "$PARENT_BLOCK" | awk -F'[<>]' '/<version>/{print $3; exit}' || true)"

            if [ -n "${PARENT_G:-}" ] && [ -n "${PARENT_A:-}" ] && [ -n "${PARENT_V:-}" ]; then
              echo "Preflight: checking parent POM ${PARENT_G}:${PARENT_A}:${PARENT_V} in CodeArtifact…"
              tmp="$(mktemp -d)"
              if ! ( cd "$tmp" && mvn -q -B -U -s "$SETTINGS_PATH" \
                     org.apache.maven.plugins:maven-dependency-plugin:3.8.0:get \
                     -DgroupId="${PARENT_G}" \
                     -DartifactId="${PARENT_A}" \
                     -Dversion="${PARENT_V}" \
                     -Dpackaging=pom \
                     -Dtransitive=false \
                     "-DremoteRepositories=ca-resolve::default::${RESOLVE_URL},ca-deps::default::${DEPS_URL}" ); then
                echo "====================================================================="
                echo "ERROR: Parent POM ${PARENT_G}:${PARENT_A}:${PARENT_V} not found in CodeArtifact."
                echo "Repos:"
                echo "  resolve=${RESOLVE_URL}"
                echo "  deps   =${DEPS_URL}"
                echo "Action:"
                echo "  • Deploy the BOM to CodeArtifact, OR"
                echo "  • Update the parent version to one that exists."
                echo "Stopping before full build."
                echo "====================================================================="
                exit 7
              fi
              echo "Preflight OK: parent POM present."
            else
              echo "WARNING: Could not parse <parent> from pom.xml; continuing."
            fi
        description: "Preflight: verify parent BOM is present in CodeArtifact"
    # --------------------------------------------------------------------

    # Build via Maven with final settings + local token; avoid Docker coupling
    - script:
        interpreter: SHELL
        scripts:
          - |
            set -e
            export CODEARTIFACT_AUTH_TOKEN="$(awk -F= '/^caToken[.]password=/{print $2}' ca-token.properties | tr -d '\r\n')"
            [ -n "${CODEARTIFACT_AUTH_TOKEN:-}" ] || { echo "ERROR: CodeArtifact token missing"; exit 1; }
            export MAVEN_OPTS="-Xms512m -Xmx1024m -Dorg.slf4j.simpleLogger.defaultLogLevel=warn"

            BRANCH_NAME="${bamboo_inject_BranchName:-develop}"
            MFE_URL="${bamboo_inject_mavenFeatureRepositoryUrl:?missing mavenFeatureRepositoryUrl}"
            PLUG_URL="${bamboo_inject_pluginRepositoryUrl:?missing pluginRepositoryUrl}"
            IS_LL="${bamboo_inject_isLongLived:-false}"

            echo "isLongLived=${IS_LL}"
            if [ "${IS_LL}" = "true" ]; then
              # Long-lived: run full ITs (expects real container behind the tests)
              mvn -s settings-final.xml -B -U clean verify \
                -P integration-test \
                "-Dbamboo.inject.BranchName=${BRANCH_NAME}" \
                "-Dbamboo.inject.mavenFeatureRepositoryUrl=${MFE_URL}" \
                "-Dbamboo.inject.pluginRepositoryUrl=${PLUG_URL}" \
                -Ddocker.skip=true \
                -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
            else
              # Short-lived (feature/develop): skip integration tests
              mvn -s settings-final.xml -B -U clean verify \
                "-Dbamboo.inject.BranchName=${BRANCH_NAME}" \
                "-Dbamboo.inject.mavenFeatureRepositoryUrl=${MFE_URL}" \
                "-Dbamboo.inject.pluginRepositoryUrl=${PLUG_URL}" \
                -DskipITs=true -Dfailsafe.skipITs=true -DfailIfNoTests=false \
                -Ddocker.skip=true \
                -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
            fi
        description: Common Build and Verify (CodeArtifact)

    # Parse Surefire & Failsafe results
    - test-parser:
        type: junit
        ignore-time: false
        test-results: "**/target/surefire-reports/*.xml"
        description: surefire reports
    - test-parser:
        type: junit
        ignore-time: false
        test-results: "**/target/failsafe-reports/*.xml"
        description: failsafe reports

    # Scripted Maven version extraction (plugin-free) and RESULT persistence
    - script:
        interpreter: SHELL
        scripts:
          - |
            set -e
            export CODEARTIFACT_AUTH_TOKEN="$(aws codeartifact get-authorization-token \
              --domain cnxsartifact --query authorizationToken --output text --region us-east-1)"

            if ! VER="$(mvn -q -s settings-ca.xml -DskipTests -Dexec.skip=true \
              org.apache.maven.plugins:maven-help-plugin:3.4.1:evaluate \
              -Dexpression=project.version -DforceStdout)"; then
              echo "maven-help (fq) failed; trying help:evaluate with -Dplugin"
              VER="$(mvn -q -s settings-ca.xml -DskipTests -Dexec.skip=true \
                help:evaluate -Dplugin=org.apache.maven.plugins:maven-help-plugin:3.4.1 \
                -Dexpression=project.version -DforceStdout || true)"
            fi
            if [ -z "${VER:-}" ]; then
              echo "help:evaluate failed; falling back to parsing POM"
              VER="$(awk 'BEGIN{RS="</project>";FS="\n"}{for(i=1;i<=NF;i++) if ($i ~ /<version>/){gsub(/^.*<version>|<\/version>.*$/,"",$i); print $i; exit}}' pom.xml)"
            fi
            [ -n "${VER:-}" ] || { echo "ERROR: could not determine Maven version"; exit 2; }
            printf 'mavenVersion=%s\n' "$VER" > maven-version.properties
            echo "Extracted mavenVersion=$VER"
        description: Extract Maven version

    - inject-variables:
        file: maven-version.properties
        scope: RESULT
        namespace: inject
        description: Inject mavenVersion (RESULT)

    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.bamboo-variable-inject-plugin:dump
        configuration: {}

    # Deploy to CodeArtifact if needed (script performs its own token handling)
    - script:
        interpreter: SHELL
        file: bamboo-deployment/deploy-to-artifactory-and-create-bamboo-version-migrate.sh
        environment: >-
          buildVersionQueryArtifact=${bamboo.buildVersionQueryArtifact}
          buildVersionQueryGroup=${bamboo.buildVersionQueryGroup}
          mavenVersion=${bamboo.inject.mavenVersion}
        description: Deploy to CodeArtifact if needed

    # Persist info for downstream plans
    - inject-variables:
        file: file.properties
        scope: RESULT
        namespace: inject
        description: Persist endpoints to RESULT

variables:
  buildVersionQueryArtifact: vendor-emulator-ear
  buildVersionQueryGroup: gov.gsa.cnxs.emulator

repositories:
  - Vendor Emulator:
      scope: global
  - bamboo-deployment:
      scope: global

triggers:
  - bitbucket-server-trigger:
      repositories:
        - Vendor Emulator

branches:
  create: for-new-branch
  delete:
    after-deleted-days: 7
    after-inactive-days: 200
  link-to-jira: true

notifications:
  - events: [plan-failed]
    recipients: [responsible, committers]
  - events: [plan-completed]
    recipients: [watchers]

labels: []

dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: none
  plans:
    - BT-WS
