apiVersion: apps/v1
kind: Deployment
metadata:
  name: avapache
  namespace: ingress-nginx
spec:
  selector:
    matchLabels:
     app.kubernetes.io/name: avapache
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: avapache
    spec:
      containers:
      - name: avapache
        image: 957770628377.dkr.ecr.us-east-1.amazonaws.com/conexus-avapache:0.2
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: avapache-config
        ports:
        - containerPort: 80
        args: [/bin/sh, -c, 'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']
