version: 2
plan:
  project-key: BT
  key: COMB
  name: Common - Build
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Default Job
Default Job:
  key: JOB1
  tasks:
  - clean
  - checkout:
      force-clean-build: true
      description: Checkout Default Repository
  - checkout:
      repository: bamboo-deployment
      path: bamboo-deployment
      force-clean-build: true
      description: Checkout Default Repository
  - script:
      interpreter: BINSH_OR_CMDEXE
      scripts:
      - rm -rf ~/.m2/repository/gov/gsa/
      description: Remove existing cnxs maven repo directory
  - script:
      interpreter: SHELL
      file: bamboo-deployment/build-determination.sh
      description: Determine parent branch and pass correct variables
  - inject-variables:
      file: file.properties
      scope: LOCAL
      namespace: inject
      description: Inject values
  - any-task:
      plugin-key: com.atlassian.bamboo.plugins.bamboo-variable-inject-plugin:dump
      configuration: {}
  - maven:
      executable: Maven 3
      jdk: JDK 17
      goal: clean verify -B -U -Dbamboo.inject.BranchName=${bamboo.inject.BranchName} -Dbamboo.inject.mavenFeatureRepositoryUrl=${bamboo.inject.mavenFeatureRepositoryUrl} -Dbamboo.inject.pluginRepositoryUrl=${bamboo.inject.pluginRepositoryUrl} -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      tests: 'true'
      description: Common Build and Verify
  - script:
      interpreter: SHELL
      file: bamboo-deployment/deploy-to-artifactory-skip-bamboo-version.sh
      environment: buildVersionQueryArtifact=${bamboo.buildVersionQueryArtifact} buildVersionQueryGroup=${bamboo.buildVersionQueryGroup} mavenVersion=${bamboo.maven.version}
      description: Determine if deploy to Artifactory is needed
# com.atlassian.bamboo.warnings.atlassian-bamboo-warnings:task.warnings.parser is disabled. This state is not supported at YAML
  artifact-subscriptions: []
repositories:
- Common:
    scope: global
- bamboo-deployment:
    scope: global
triggers:
- bitbucket-server-trigger:
    repositories:
    - Common
branches:
  create: for-new-branch
  delete:
    after-deleted-days: 7
    after-inactive-days: 90
  link-to-jira: true
notifications:
- events:
  - plan-failed
  recipients:
  - responsible
  - committers
- events:
  - plan-completed
  recipients:
  - watchers
- events:
  - plan-failed
  recipients:
  - responsible
  - committers
labels: []
dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: block_if_parent_in_progress
  plans:
  - BT-WSCLIEN
  - BT-DOMB
---
version: 2
plan:
  key: BT-COMB
plan-permissions:
- users:
  - simon.branton-housley@usda.gov
  groups:
  - nsfs_devops
  permissions:
  - view
  - edit
  - build
  - clone
  - admin
  - view-configuration