<?xml version="1.0" encoding="UTF-8" standalone="yes"?><specs><spec projectKey="BT" buildKey="PRIC"><code>---
version: 2
plan:
  project-key: BT
  key: PRIC
  name: Pricing - Build
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Default Job
Default Job:
  key: JOB1
  other:
    clean-working-dir: true
    all-other-apps:
      custom:
        auto: {}
        buildHangingConfig.enabled: 'false'
  tasks:
# com.atlassian.bamboo.plugins.bamboo-docker-plugin:task.docker.cli is disabled. This state is not supported at YAML
  - checkout:
      force-clean-build: true
      description: Checkout Default Repository
  - checkout:
      repository: bamboo-deployment
      path: bamboo-deployment
      force-clean-build: true
      description: Checkout Default Repository
  - script:
      interpreter: BINSH_OR_CMDEXE
      scripts:
      - "#rm -rf ~/.m2/repository/gov/gsa/cnxs/\n#Bas: made below change; this only deletes snapshot folders so we don't download\n# the big released datafile artifact each time.\ndirName=~/.m2/repository/gov/gsa/\nif [ -d \"$dirName\" ]; then\n\techo \"Removing snapshot folders from $dirName\"\n    find \"$dirName\" -type d -name '*SNAPSHOT' -exec rm -rf {} +\nfi"
      description: Remove existing cnxs maven repo directory
  - script:
      interpreter: SHELL
      file: bamboo-deployment/build-determination.sh
      description: Determine parent branch and pass correct variables
  - inject-variables:
      file: file.properties
      scope: LOCAL
      namespace: inject
      description: Inject values
  - any-task:
      plugin-key: com.atlassian.bamboo.plugins.bamboo-variable-inject-plugin:dump
      configuration: {}
  - maven:
      executable: Maven 3
      jdk: JDK 17
      goal: clean verify -B -U -P integration-test -Dbamboo.inject.BranchName=${bamboo.inject.BranchName} -Dbamboo.inject.mavenFeatureRepositoryUrl=${bamboo.inject.mavenFeatureRepositoryUrl} -Dbamboo.inject.pluginRepositoryUrl=${bamboo.inject.pluginRepositoryUrl} -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      tests: '**/target/surefire-reports/*.xml,**/target/failsafe-reports/*.xml'
      environment: MAVEN_OPTS="-Xms512m -Xmx1024m"
      description: Build and Verify
  - script:
      interpreter: SHELL
      file: bamboo-deployment/deploy-to-artifactory-skip-bamboo-version.sh
      environment: buildVersionQueryArtifact=${bamboo.buildVersionQueryArtifact} buildVersionQueryGroup=${bamboo.buildVersionQueryGroup} mavenVersion=${bamboo.maven.version}
      description: Deploy to Artifactory if needed
  artifact-subscriptions: []
repositories:
- Pricing:
    scope: global
- bamboo-deployment:
    scope: global
triggers:
- bitbucket-server-trigger:
    repositories:
    - Pricing
branches:
  create: for-new-branch
  delete:
    after-deleted-days: 7
    after-inactive-days: 200
  link-to-jira: true
notifications:
- events:
  - plan-failed
  recipients:
  - responsible
  - committers
- events:
  - plan-completed
  recipients:
  - watchers
- events:
  - plan-failed
  recipients:
  - responsible
  - committers
labels: []
dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: none
  plans:
  - BT-REC
  - BT-REST
other:
  concurrent-build-plugin:
    number-of-concurrent-builds: system-default
    execution-strategy: block-triggering
---
version: 2
plan:
  key: BT-PRIC
plan-permissions:
- users:
  - simon.branton-housley@usda.gov
  groups:
  - nsfs_devops
  permissions:
  - view
  - edit
  - build
  - clone
  - admin
  - view-configuration
  - create-plan-branch
...
</code></spec></specs>