<?xml version="1.0" encoding="UTF-8" standalone="yes"?><specs><spec projectKey="BT" buildKey="SB"><code>---
version: 2
plan:
  project-key: BT
  key: SB
  name: Schema - Build
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Default Job
Default Job:
  key: JOB1
  other:
    clean-working-dir: true
    all-other-apps:
      custom:
        auto: {}
        buildHangingConfig.enabled: 'false'
  tasks:
  - checkout:
      force-clean-build: true
      description: Checkout Default Repository
  - checkout:
      repository: bamboo-deployment
      path: bamboo-deployment
      force-clean-build: true
      description: Checkout Default Repository
  - script:
      interpreter: BINSH_OR_CMDEXE
      scripts:
      - "#rm -rf ~/.m2/repository/gov/gsa/cnxs/\n#Bas: made below change; this only deletes snapshot folders so we don't download\n# the big released datafile artifact each time.\ndirName=~/.m2/repository/gov/gsa/cnxs/\nif [ -d \"$dirName\" ]; then\n\techo \"Removing snapshot folders from $dirName\"\n    find \"$dirName\" -type d -name '*SNAPSHOT' -exec rm -rf {} +\nfi"
      description: Remove existing cnxs maven repo directory
  - script:
      interpreter: SHELL
      file: bamboo-deployment/build-determination.sh
      description: Determine parent branch and pass correct variables
  - inject-variables:
      file: file.properties
      scope: LOCAL
      namespace: inject
      description: Inject values
  - maven:
      executable: Maven 3
      jdk: JDK 17
      goal: clean verify -U -Dbamboo.inject.BranchName=${bamboo.inject.BranchName} -Dbamboo.inject.mavenFeatureRepositoryUrl=${bamboo.inject.mavenFeatureRepositoryUrl} -Dbamboo.inject.pluginRepositoryUrl=${bamboo.inject.pluginRepositoryUrl}
      description: Common Build and Verify
  - any-task:
      plugin-key: com.davidehringer.atlassian.bamboo.maven.maven-pom-parser-plugin:maven-pom-parser-plugin
      configuration:
        gavOrCustom: '0'
        variableType: '2'
        prefixOption: '1'
  - script:
      interpreter: SHELL
      file: bamboo-deployment/deploy-to-artifactory-skip-bamboo-version.sh
      description: Determine if deploy to Artifactory is needed
  artifact-subscriptions: []
repositories:
- Schema:
    scope: global
- bamboo-deployment:
    scope: global
triggers:
- bitbucket-server-trigger:
    repositories:
    - Schema
branches:
  create: for-new-branch
  delete:
    after-deleted-days: 30
    after-inactive-days: 200
  link-to-jira: true
notifications:
- events:
  - plan-completed
  recipients:
  - watchers
- events:
  - plan-failed
  recipients:
  - responsible
  - committers
labels: []
dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: block_if_parent_in_progress
  plans: []
other:
  concurrent-build-plugin:
    number-of-concurrent-builds: system-default
    execution-strategy: block-triggering
  force-stop-build: true
---
version: 2
plan:
  key: BT-SB
plan-permissions:
- users:
  - simon.branton-housley@usda.gov
  groups:
  - nsfs_devops
  permissions:
  - view
  - edit
  - build
  - clone
  - admin
  - view-configuration
  - create-plan-branch
...
</code></spec></specs>