<?xml version="1.0" encoding="UTF-8" standalone="yes"?><specs><spec projectKey="CC" buildKey="EDT"><code>---
version: 2
plan:
  project-key: CC
  key: EDT
  name: Env - Unified Clover Build
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Default Job
Default Job:
  key: JOB1
  other:
    all-other-apps:
      custom:
        auto: {}
        buildHangingConfig.enabled: 'false'
        clover:
          path: target/site/clover/**/clover.xml
          integration: auto
          exists: 'true'
          tool: openclover
  tasks:
  - checkout:
      force-clean-build: true
      description: Checkout Default Repository
  - checkout:
      repository: bamboo-deployment
      path: bamboo-deployment
      force-clean-build: true
      description: Checkout Default Repository
  - script:
      interpreter: BINSH_OR_CMDEXE
      scripts:
      - rm -rf ~/.m2/repository/gov/gsa/cnxs/
      description: Remove existing cnxs maven repo directory
  - script:
      interpreter: SHELL
      file: bamboo-deployment/build-determination.sh
      description: Determine parent branch and pass correct variables
  - inject-variables:
      file: file.properties
      scope: LOCAL
      namespace: inject
      description: Inject values
  - maven:
      executable: Maven 3
      jdk: JDK 17
      goal: clean verify -U -Dbamboo.inject.BranchName=${bamboo.inject.BranchName} -Dbamboo.inject.mavenFeatureRepositoryUrl=${bamboo.inject.mavenFeatureRepositoryUrl} -Dbamboo.inject.pluginRepositoryUrl=${bamboo.inject.pluginRepositoryUrl} -Dmaven.clover.repositoryPollutionProtection=false
      tests: 'true'
  artifacts:
  - name: Clover Report (System)
    location: target/site/clover
    pattern: '**/*.*'
    shared: false
    required: false
  artifact-subscriptions: []
variables:
  ssc_applicationName: Conexus-Task
  ssc_applicationVersion: '1.0'
  ssc_applicationVersionId: '14'
repositories:
- Env:
    scope: global
- bamboo-deployment:
    scope: global
triggers:
- cron:
    expression: 0 0 5 ? * 5,2,6,3,4
    description: weekly morning
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: []
labels: []
dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: none
  plans: []
other:
  concurrent-build-plugin:
    number-of-concurrent-builds: system-default
    execution-strategy: block-triggering
---
version: 2
plan:
  key: CC-EDT
plan-permissions:
- users:
  - simon.branton-housley@usda.gov
  groups:
  - nsfs_devops
  permissions:
  - view
  - edit
  - build
  - clone
  - admin
  - view-configuration
  - create-plan-branch
...
</code></spec></specs>