#!/usr/bin/bash
#
# conexussftp	Startup script for scannmove
#
# chkconfig: 2345 99 01
# description: Virus scans and moves files between sftp and database.
### BEGIN INIT INFO
# Provides:          conexussftp-server
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: SFTP ScanNmove daemon
# Description:       This is a daemon that controls the SFTP Watchdog daemon.
### END INIT INFO

# source function library
. /etc/init.d/functions
RETVAL=0
APP_DIR="/app/ConexusSFTP"
prog=scannmovewrapper

if [ -x $APP_DIR/process/scannmovewrapper ]; then
    exec="$APP_DIR/process/scannmovewrapper"
else
    exit 5
fi

PIDFILE=/var/run/conexussftp.pid
lockfile=/var/lock/subsys/conexussftp

start() {

    pid=
    if [ -f $PIDFILE ]; then

	pid=$(cat $PIDFILE)
	echo -n "Pid $PIDFILE exist";
	RETVAL=1

    else
    
	echo -n $"Starting ConexusSFTP : "
	nohup $exec >/dev/null 2>&1 &
	RETVAL=$?
	echo $! > $PIDFILE
	echo
	[ $RETVAL -eq 0 ] && touch ${lockfile}

    fi
    
    return $RETVAL

}


stop() {
    pid=$(cat $PIDFILE)
    echo -n $"Stopping ConexusSFTP : "
        killproc -p "$PIDFILE" $exec
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f $lockfile
        
        while $(kill -0 ${pid} 2>/dev/null); do
	  printf "SIGTERM sent to ${pid}\n"  
          printf "Waiting for ConexusSFTP to die...\n"
          sleep 1
        done
        return $RETVAL
}

rhstatus() {
        status -p "$PIDFILE" -l $prog $exec
}

restart() {
   stop
   start
}

# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
        rhstatus
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 3
esac

exit $?


