ARG BASE_REGISTRY=registry1.dso.mil
ARG BASE_IMAGE=ironbank/redhat/ubi/ubi9-minimal
ARG BASE_TAG=9.5

FROM ${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_TAG}

RUN microdnf -y update && \
    microdnf -y upgrade && \
    microdnf -y install httpd mod_ssl mod_session pip && \
    microdnf -y clean all
