#!/usr/bin/perl --
use strict;
use warnings;
use CGI;

print qq!Content-type: text/html\n\n!;
=pod
my $q = CGI->new;
my %headers = map { $_ => $q->http($_) } $q->http();

print $q->header('text/plain');
print "Got the following headers:\n";
for my $header ( keys %headers ) {
    print "$header: $headers{$header}\n";
}
=cut

print qq!Non CGI lib, raw ENV\n!;
for my $ekey (keys %ENV) {
    print qq!$ekey : $ENV{$ekey} : \n!;
}
